### ISSUE TITLE
opkg update no longer works

### ISSUE THREAD

**Issue by jonahweissman** [toltec-dev/toolchain#7]
In v1.3.1, if I run `opkg update`, I can install packages. However, in v1.3.2, `opkg update` exits without an error, but does not seem to actually update the package list. If I run `opkg install libc`, for example, it fails with `  * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'libc'` . I believe this has to do with `/etc/opkg` moving to $SYSROOT, since that's really all that changed between v1.3.1 and v1.3.2.

**Comment by matteodelabre** [comment]
Hi Jonah, thanks for the report. In 1.3.2 you need to add the `--offline-root $SYSROOT` flag to all opkg invocations. This change prevents opkg from trying to run the postinstall scripts of the installed packages, since they are only meant to be run on the target device. Sorry that this was not documented.

**Comment by jonahweissman** [comment]
Thanks! That makes sense. Do you think we should set up an alias or a wrapper script so that calls to `opkg` get that flag added automatically? I'm thinking it would eliminate the need to document that requirement and would keep recipes less verbose.

**Comment by matteodelabre** [comment]
That’s a good point, but we’d probably need to document the fact that maintainer scripts are not invoked anyway.

**Comment by matteodelabre** [comment]
Fixed in v1.4.
